[build]
  command = "npm ci"
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"
  # POZOR: žádný `external_node_modules` sem nedávej – chceme cheerio zabalit dovnitř.
