[build]
  command = "npm i"
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"
  # nic dalšího sem nedávej (žádné external_node_modules)
